setwd("E:/SARS-CoV-2/REDO/la_b117")
dat <- read.csv("la_b117_counts.csv")
names(dat) <- c("count")
d <- density(dat$count)
pdf("kdp_B117_la.pdf")
plot(d, main="B.1.1.7 in LA County", xlab="Time (days)", ylab="Density of Total Population")
polygon(d, col="red", border="black")
abline(v=c(82), lty=2)
dev.off()