setwd("E:/SARS-CoV-2/REDO/repo/kdp")
dat <- read.csv("hi_b117_counts.csv")
names(dat) <- c("count")
d <- density(dat$count)
pdf("kdp_B117_hi_v2.pdf")
plot(d, main="B.1.1.7 in Hawai'i", xlab="Time (days)", ylab="Density of Total Population")
polygon(d, col="red", border="black")
abline(v=c(97), lty=2)
dev.off()

setwd("E:/SARS-CoV-2/REDO/repo/kdp")
dat <- read.csv("la_b117_counts.csv")
names(dat) <- c("count")
d <- density(dat$count)
pdf("kdp_B117_la_v2.pdf")
plot(d, main="B.1.1.7 in LA County", xlab="Time (days)", ylab="Density of Total Population")
polygon(d, col="red", border="black")
abline(v=c(82), lty=2)
dev.off()

setwd("E:/SARS-CoV-2/REDO/repo/kdp")
dat <- read.csv("hi_b1243_counts.csv")
names(dat) <- c("count")
d <- density(dat$count)
pdf("kdp_B1243_hi_v2.pdf")
plot(d, main="B.1.243 in Hawai'i", xlab="Time (days)", ylab="Density of Total Population")
polygon(d, col="red", border="black")
abline(v=c(165), lty=2)
dev.off()

setwd("E:/SARS-CoV-2/REDO/repo/kdp")
dat <- read.csv("la_b1243_counts.csv")
names(dat) <- c("count")
d <- density(dat$count)
pdf("kdp_B1243_la_v2.pdf")
plot(d, main="B.1.243 in LA County", xlab="Time (days)", ylab="Density of Total Population")
polygon(d, col="red", border="black")
abline(v=c(184), lty=2)
dev.off()
